import {buildFqpDetails,normalizeCode} from './fqp-core.js';
const relations=[['connection','Conexão'],['stopover','Stopover'],['surface','Surface'],['stopover-surface','Stopover + Surface']];
let segments=[{origin:'CWB',destination:'GRU',date:'2025-07-28',airline:'AC',bookingClass:'K',relation:'connection'},{origin:'GRU',destination:'YUL',date:'2025-07-28',airline:'AC',bookingClass:'K',relation:'stopover'},{origin:'YUL',destination:'GRU',date:'2025-11-30',airline:'AC',bookingClass:'T',relation:'connection'},{origin:'GRU',destination:'CWB',date:'2025-12-01',airline:'AC',bookingClass:'T',relation:'connection'}];
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function read(){segments=[...document.querySelectorAll('.segment')].map(card=>Object.fromEntries([...card.querySelectorAll('[data-field]')].map(input=>[input.dataset.field,input.value])))}
function preview(){if(!segments.length)return '';let value=normalizeCode(segments[0].origin)||'???';segments.forEach((s,i)=>{value+=` → ${normalizeCode(s.destination)||'???'}`;const next=segments[i+1];if(!next)return;if(s.relation==='stopover')value+=` | STOPOVER | ${normalizeCode(next.origin)||'???'}`;if(s.relation==='surface')value+=` | SURFACE ${normalizeCode(s.destination)||'???'} → ${normalizeCode(next.origin)||'???'} | ${normalizeCode(next.origin)||'???'}`;if(s.relation==='stopover-surface')value+=` | STOPOVER + SURFACE ${normalizeCode(s.destination)||'???'} → ${normalizeCode(next.origin)||'???'} | ${normalizeCode(next.origin)||'???'}`});return value}
function result(){read();const built=buildFqpDetails(segments,$('#issueDate').value);$('#preview').textContent=preview();$('#command').textContent=built.command||'Complete os campos obrigatórios.';$('#copy').disabled=!built.valid;$('#messages').innerHTML=[...built.errors.map(x=>`<p class="error">${esc(x)}</p>`),...built.warnings.map(x=>`<p class="warning">${esc(x)}</p>`)].join('');$('#breakdown').innerHTML=built.parts.map(x=>`<div><b>${esc(x.label)}</b><code>${esc(x.value)}</code></div>`).join('')}
function render(){ $('#segments').innerHTML=segments.map((s,i)=>`<article class="segment" data-index="${i}"><div class="segment-head"><h3>Trecho ${i+1}</h3><div><button data-move="-1" ${i?'':'disabled'}>↑</button><button data-move="1" ${i<segments.length-1?'':'disabled'}>↓</button><button class="remove" ${segments.length>1?'':'disabled'}>Remover</button></div></div><div class="fields"><label>Origem<input data-field="origin" maxlength="3" value="${esc(s.origin)}" placeholder="CWB"></label><label>Destino<input data-field="destination" maxlength="3" value="${esc(s.destination)}" placeholder="GRU"></label><label>Data<input data-field="date" type="date" value="${esc(s.date)}"></label><label>Cia<input data-field="airline" maxlength="2" value="${esc(s.airline)}" placeholder="AC"></label><label>Classe<input data-field="bookingClass" maxlength="1" value="${esc(s.bookingClass)}" placeholder="K"></label></div>${i<segments.length-1?`<label class="relation">Relação com o próximo trecho<select data-field="relation">${relations.map(([v,l])=>`<option value="${v}" ${s.relation===v?'selected':''}>${l}</option>`).join('')}</select></label>`:''}</article>`).join('');result()}
$('#issueDate').value='2025-05-19';render();
document.body.addEventListener('input',e=>{if(e.target.matches('input[data-field]:not([type=date])'))e.target.value=normalizeCode(e.target.value).replace(/[^A-Z0-9]/g,'');result()});document.body.addEventListener('change',result);
$('#addSegment').onclick=()=>{read();const last=segments.at(-1);segments.push({origin:last?.destination||'',destination:'',date:last?.date||'',airline:last?.airline||'',bookingClass:last?.bookingClass||'',relation:'connection'});render()};
$('#segments').onclick=e=>{const button=e.target.closest('button');if(!button)return;read();const index=Number(button.closest('.segment').dataset.index);if(button.classList.contains('remove'))segments.splice(index,1);else{const target=index+Number(button.dataset.move);[segments[index],segments[target]]=[segments[target],segments[index]]}render()};
$('#copy').onclick=async()=>{const value=$('#command').textContent;await navigator.clipboard.writeText(value);$('#copyStatus').textContent='FQP copiado!';setTimeout(()=>$('#copyStatus').textContent='',2000)};
