import {buildFqpDetails,normalizeCode} from './fqp-core.js';
const relations=[['connection','Conexão'],['stopover','Stopover'],['surface','Surface']];
const emptySegment=()=>({origin:'',destination:'',date:'',airline:'',bookingClass:'',relation:'connection'});
let segments=[emptySegment()];
let showValidation=false;
let familyMode='none',globalFareFamily='';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function formatBrDateInput(value){const digits=String(value??'').replace(/\D/g,'').slice(0,8);return digits.length>4?`${digits.slice(0,2)}/${digits.slice(2,4)}/${digits.slice(4)}`:digits.length>2?`${digits.slice(0,2)}/${digits.slice(2)}`:digits}
function read(){segments=[...document.querySelectorAll('.segment')].map(card=>Object.fromEntries([...card.querySelectorAll('[data-field]')].map(input=>[input.dataset.field,input.value])))}
function preview(){if(!segments.length||segments.every(s=>!s.origin&&!s.destination))return 'O itinerário aparecerá aqui conforme o preenchimento.';let value=normalizeCode(segments[0].origin)||'???';segments.forEach((s,i)=>{value+=` → ${normalizeCode(s.destination)||'???'}`;const next=segments[i+1];if(!next)return;if(s.relation==='stopover')value+=` | STOPOVER | ${normalizeCode(next.origin)||'???'}`;if(s.relation==='surface')value+=` | SURFACE ${normalizeCode(s.destination)||'???'} → ${normalizeCode(next.origin)||'???'} | ${normalizeCode(next.origin)||'???'}`});return value}
function result(){read();globalFareFamily=$('#globalFareFamily').value;const built=buildFqpDetails(segments,$('#issueDate').value,{fareFamilyMode:familyMode,fareFamily:globalFareFamily});$('#preview').textContent=preview();$('#command').textContent=built.command||'Complete os campos obrigatórios.';$('#copy').disabled=!built.valid;const errors=showValidation&&built.errors.length?`<div class="error"><strong>Revise os campos:</strong><ul>${built.errors.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:'';const warnings=showValidation&&built.warnings.length?`<div class="warning">${built.warnings.map(x=>`<p>${esc(x)}</p>`).join('')}</div>`:'';$('#messages').innerHTML=errors+warnings;$('#breakdown').innerHTML=built.parts.map(x=>`<div><b>${esc(x.label)}</b><code>${esc(x.value)}</code></div>`).join('')}
function render(){ $('#segments').innerHTML=segments.map((s,i)=>`<div class="segment-block"><article class="segment" data-index="${i}" data-number="${i+1}"><div class="segment-head"><h3>Trecho ${i+1}</h3><div><button data-move="-1" ${i?'':'disabled'} aria-label="Mover para cima">↑</button><button data-move="1" ${i<segments.length-1?'':'disabled'} aria-label="Mover para baixo">↓</button><button class="remove" ${segments.length>1?'':'disabled'}>Remover</button></div></div><div class="fields"><label>Origem<input data-field="origin" maxlength="3" value="${esc(s.origin)}" placeholder="GRU"></label><label>Destino<input data-field="destination" maxlength="3" value="${esc(s.destination)}" placeholder="MIA"></label><label>Data<input data-field="date" type="text" inputmode="numeric" maxlength="10" value="${esc(s.date)}" placeholder="dd/mm/aaaa" autocomplete="off"></label><label>Cia<input data-field="airline" maxlength="2" value="${esc(s.airline)}" placeholder="LA"></label><label>Classe<input data-field="bookingClass" maxlength="1" value="${esc(s.bookingClass)}" placeholder="Y"></label></div>${familyMode==='segment'?`<label class="segment-family">Família tarifária deste trecho<input data-field="fareFamily" maxlength="20" value="${esc(s.fareFamily||'')}" placeholder="ECONO" autocomplete="off" spellcheck="false"></label>`:''}${i<segments.length-1?`<label class="relation">Relação com o próximo trecho<select data-field="relation">${relations.map(([v,l])=>`<option value="${v}" ${s.relation===v?'selected':''}>${l}</option>`).join('')}</select></label>`:''}</article><button class="insert" data-add-after="${i}" type="button"><span>+</span> Adicionar trecho aqui</button></div>`).join('');result()}
render();
document.body.addEventListener('input',e=>{showValidation=true;if(e.target.matches('[data-field="date"],#issueDate'))e.target.value=formatBrDateInput(e.target.value);else if(e.target.matches('[data-field="origin"],[data-field="destination"],[data-field="airline"],[data-field="bookingClass"],[data-field="fareFamily"],#globalFareFamily'))e.target.value=normalizeCode(e.target.value).replace(/[^A-Z0-9]/g,'');result()});document.body.addEventListener('change',()=>{showValidation=true;result()});
$('#familyMode').onchange=()=>{read();familyMode=$('#familyMode').value;$('#globalFamilyField').hidden=familyMode!=='global';render()};
$('#segments').onclick=e=>{const button=e.target.closest('button');if(!button)return;showValidation=true;read();if(button.classList.contains('insert')){const after=Number(button.dataset.addAfter),next=emptySegment();next.origin=segments[after].destination;segments.splice(after+1,0,next);render();document.querySelector(`.segment[data-index="${after+1}"] [data-field="destination"]`)?.focus();return}const index=Number(button.closest('.segment').dataset.index);if(button.classList.contains('remove'))segments.splice(index,1);else{const target=index+Number(button.dataset.move);[segments[index],segments[target]]=[segments[target],segments[index]]}render()};
$('#copy').onclick=async()=>{const value=$('#command').textContent;await navigator.clipboard.writeText(value);$('#copyStatus').textContent='FQP copiado!';setTimeout(()=>$('#copyStatus').textContent='',2000)};
